import { api } from "@/lib/api";
import SentimentBadge from "@/components/SentimentBadge";
import { Lightbulb, CheckCircle, Users, Hash } from "lucide-react";

export const dynamic = "force-dynamic";

const PRIORITY_STYLES: Record<string, string> = {
  high:   "border-l-4 border-sp-negative",
  medium: "border-l-4 border-yellow-400",
  low:    "border-l-4 border-sp-green",
};

export default async function OpportunitiesPage() {
  let data: any = {};
  try { data = await api.opportunities(); } catch {}

  const opps: any[] = data.opportunities ?? [];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-sp-white">Product Opportunities</h1>
        <p className="text-sp-light-gray text-sm mt-1">
          {opps.length} prioritised recommendations generated by Groq Llama 3.3 70B
        </p>
      </div>

      {opps.length === 0 && (
        <div className="flex flex-col items-center justify-center h-64 gap-4 bg-sp-dark rounded-sp">
          <Lightbulb size={40} className="text-sp-mid-gray" />
          <p className="text-sp-light-gray text-sm">No opportunities yet.</p>
          <code className="text-sp-green text-xs bg-sp-gray px-3 py-1.5 rounded">
            python -m src.pipeline aggregate
          </code>
        </div>
      )}

      <div className="space-y-4">
        {opps.map((opp: any, i: number) => (
          <div
            key={i}
            className={`bg-sp-dark rounded-sp p-6 ${PRIORITY_STYLES[opp.priority] ?? ""} hover:bg-sp-gray/30 transition-colors`}
          >
            {/* Header */}
            <div className="flex items-start justify-between gap-4 mb-4">
              <div className="flex items-center gap-3">
                <span className="bg-sp-green/20 text-sp-green text-xs font-bold w-7 h-7 rounded-full flex items-center justify-center">
                  {i + 1}
                </span>
                <h3 className="text-sp-white font-bold text-lg">{opp.title}</h3>
              </div>
              <SentimentBadge value={opp.priority} />
            </div>

            {/* Problem statement */}
            <p className="text-sp-light-gray text-sm mb-4">{opp.problem_statement}</p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Evidence */}
              {opp.evidence?.length > 0 && (
                <div>
                  <p className="text-sp-white text-xs font-semibold uppercase tracking-wider mb-2">Evidence</p>
                  <ul className="space-y-1">
                    {opp.evidence.map((e: string, j: number) => (
                      <li key={j} className="flex items-start gap-2 text-sp-light-gray text-sm">
                        <span className="text-sp-green mt-0.5">→</span>
                        {e}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Recommendation */}
              <div>
                <p className="text-sp-white text-xs font-semibold uppercase tracking-wider mb-2">Recommendation</p>
                <p className="text-sp-light-gray text-sm leading-relaxed">{opp.recommendation}</p>
              </div>
            </div>

            {/* Footer tags */}
            <div className="flex items-center gap-4 mt-4 pt-4 border-t border-sp-gray">
              {opp.affected_segments?.length > 0 && (
                <div className="flex items-center gap-1.5">
                  <Users size={12} className="text-sp-mid-gray" />
                  {opp.affected_segments.map((s: string) => (
                    <span key={s} className="text-xs bg-sp-gray text-sp-light-gray px-2 py-0.5 rounded-full capitalize">
                      {s.replace(/_/g, " ")}
                    </span>
                  ))}
                </div>
              )}
              {opp.themes?.length > 0 && (
                <div className="flex items-center gap-1.5">
                  <Hash size={12} className="text-sp-mid-gray" />
                  {opp.themes.map((t: string) => (
                    <span key={t} className="text-xs bg-sp-green/10 text-sp-green px-2 py-0.5 rounded-full capitalize">
                      {t.replace(/_/g, " ")}
                    </span>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
